### ISSUE TITLE
MMM-MyGarbage module shows Loading

### ISSUE THREAD

**Issue by jdlucke** [htilburgs/MMM-MyGarbage#10]
I know that others have had this issue, and I have tried the changes suggested, but here is my challenge:

Error received: 
0|MagicMirror  | [12.11.2021 16:42.10.024] [ERROR] 
0|MagicMirror  | TypeError: Cannot read property 'isSameOrAfter' of undefined
0|MagicMirror  |     at /home/pi/MagicMirror/modules/MMM-MyGarbage/node_helper.js:63:24
0|MagicMirror  |     at Array.filter (<anonymous>:null:null)
0|MagicMirror  |     at Class.getNextPickups (/home/pi/MagicMirror/modules/MMM-MyGarbage/node_helper.js:61:42)
0|MagicMirror  |     at /home/pi/MagicMirror/modules/MMM-MyGarbage/node_helper.js:34:18
0|MagicMirror  |     at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-MyGarbage/node_modules/csv-parse/lib/index.js:941:7)
0|MagicMirror  |     at Parser.emit (events.js:315:20)
0|MagicMirror  |     at endReadableNT (internal/streams/readable.js:1327:12)
0|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:80:21)

Here is the CSV File:
WeekStarting,gray,blue
11/05/21,1,0
11/12/21,1,1
11/19/21,1,0
11/26/21,1,1
12/03/21,1,0
12/10/21,1,1
12/17/21,1,0
12/24/21,1,1
12/31/21,1,0
01/07/22,1,1
01/14/22,1,0
01/21/22,1,1
01/28/22,1,0
02/04/22,1,1
02/11/22,1,0
02/18/22,1,1
02/25/22,1,0
03/04/22,1,1
03/11/22,1,0
03/18/22,1,1
03/25/22,1,0
04/01/22,1,1
04/08/22,1,0
04/15/22,1,1
04/22/22,1,0
04/29/22,1,1
05/06/22,1,0
05/13/22,1,1
05/20/22,1,0
05/27/22,1,1
06/03/22,1,0

Here is the config.js file module:{
297                 module: 'MMM-MyGarbage',
298                 position: 'top_right',
299                 header: 'My Garbage Calendar',
300                         config: {
301                                 alert: 4,
302                                 weeksToDisplay: 10,
303                                 limitTo: 99,
304                                 fade: true,
305                                 dateFormat: "dddd D MMMM",
306                                 fadePoint: 0.25
307                                 }
308         },

What I get is the header followed by Loading....

**Comment by TDMPro2K** [comment]
I have also got it saying loading for no reason.  Was working one day and not the next.

**Comment by mickecamino** [comment]
Check that you only have one line extra at the end in the garbage_schedule.csv. If you have two it wont work

**Comment by htilburgs** [comment]
garbage_schedule.csv needs 6 items (update 12-06-2023), so it looks like:

WeekStarting,GreenBin,GarbageBin,PaperBin,PMDBin,OtherBin
06/13/23,1,0,0,0,0
06/14/23,0,1,0,0,0
06/15/23,0,0,1,0,0
06/16/23,0,0,0,1,0
06/17/23,0,0,0,0,1
