### ISSUE TITLE
Module says "Loading"

### ISSUE THREAD

**Issue by ibipp** [htilburgs/MMM-MyGarbage#6]
Hi,
There is only the example csv file who is working. When i change something, the module gives out: "Loading" but nothing is loaded. 
Here is my file i want to have in place. What do i wrong?

WeekStarting,#FFFF00,#2E2E2E,#FFFFFF
10/14/2019,1,0,0
10/15/2019,0,1,0
10/28/2019,1,0,0
10/29/2019,0,1,0
11/11/2019,1,0,0
11/12/2019,0,1,0
11/25/2019,1,0,0
11/26/2019,0,1,0
12/09/2019,1,0,0
12/10/2019,0,1,0
12/23/2019,1,0,0
12/24/2019,0,1,0
01/06/2020,1,0,0
01/07/2020,0,1,0
01/20/2020,1,0,0
01/21/2020,0,1,0
02/03/2020,1,0,0
02/04/2020,0,1,0
02/17/2020,1,0,0
02/18/2020,0,1,0
03/02/2020,1,0,0
03/03/2020,0,1,0
03/16/2020,1,0,0
03/17/2020,0,1,0
03/30/2020,1,0,0
03/31/2020,0,1,0
04/13/2020,1,0,0
04/14/2020,0,1,0
04/27/2020,1,0,0
04/28/2020,0,1,0
05/11/2020,1,0,0
05/12/2020,0,1,0
05/25/2020,1,0,0
05/26/2020,0,1,0
06/08/2020,1,0,0
06/09/2020,0,1,0
06/22/2020,1,0,0
06/23/2020,0,1,0
07/06/2020,1,0,0
07/07/2020,0,1,0
07/20/2020,1,0,0
07/21/2020,0,1,0
08/03/2020,1,0,0
08/04/2020,0,1,0
08/17/2020,1,0,0
08/18/2020,0,1,0
08/31/2020,1,0,0
09/01/2020,0,1,0
09/14/2020,1,0,0
09/15/2020,0,1,0
09/28/2020,1,0,0
09/29/2020,0,1,0
10/12/2020,1,0,0
10/13/2020,0,1,0
10/26/2020,1,0,0
10/27/2020,0,1,0

Ah yeah, ive putted an 3 bin i dont needed, just to come close to the example.csv file. 

Thank you for helping,
PS: very cool module ;)

**Comment by htilburgs** [comment]
As stated in the readme, the date format needs to be specified as MM/DD/YY (e.g.: 05/28/18 for 28-May-2018). Can you change the dates from 10/14/2019 to 10/14/19 and try again?

**Comment by ibipp** [comment]
Sorry, for my idiocy!!
Thank you for your work!

**Comment by htilburgs** [comment]
Great I could help you and thanks!

**Comment by MetroAffe** [comment]
Same Problem here. File lokks like this:
WeekStarting,green,gray,blue
03/07/20,1,0,1
03/14/20,1,1,1
03/21/20,1,0,1
03/28/20,1,1,1

If I remove all lines after the second it works... dont know why?

**Comment by htilburgs** [comment]
@MetroAffe, I've loaded your config, but I don't see any issues!
But maybe you see only 2 lines? If that is the case look at your config:

>                {
>                         module: 'MMM-MyGarbage',
>                         position: 'top_left',
>                         header: 'Afvalkalender Cure',
>                         disabled: false,
>                         config: {
>                                 weeksToDisplay: 4,
>                                 limitTo: 99,
>                                 dateFormat: "dddd LL",
>                                 fade: false,
>                                 fadePoint: 0.25
>                                 }
>                 },
> 

There is a line **"weeksToDisplay: 4,"** This maybe you're problem?
Because the module looks only 4 weeks ahead it looks for you that it's not working correct.
Try to change this into **"weeksToDisplay: 10,"** and see what happens and let me know.

**Comment by MetroAffe** [comment]
Great job! Works now for me...
I thought I already tried this Option. Hmmm shit happens :)

Thanks for your help

**Comment by htilburgs** [comment]
@MetroAffe 
I'm glad it worked out. Enjoy this module!
