### ISSUE TITLE
Width is driven off of the length of the header text

### ISSUE THREAD

**Issue by dhcrain** [htilburgs/MMM-MyGarbage#7]
If you have a short, or no, header the date and garbage icons overlap. 
Should the width be driven off of the content of `.garbage-container`?

**Comment by bertdeelman** [comment]
Add: 

`.MMM-MyGarbage .module-content {
  width: 350px; /* adjust this to taste */
}`

at custom.css

**Comment by htilburgs** [comment]
as Bert Deelman says

Add:

.MMM-MyGarbage .module-content { width: 350px; /* adjust this to taste */ }

at custom.css
