### ISSUE TITLE
Request to show different waste Icons

### ISSUE THREAD

**Issue by BlueForrest** [htilburgs/MMM-MyGarbage#9]
Hi, like this garbage module, but How to change Icons?  Now I can only change color of the wastebin Icon, but I would like to have a different icon for each type of waste.

- Green Waste
- Garbage
- Glass
- Paper
- Plastic 
Would that be possible ?
I don't know how to implement or modify this - hope you can do that.

thx.

**Comment by MacG-DD** [comment]
Maybe with the custom.css. It will probably be difficult. There you can distinguish the icons only by the color assigned in the CSV.
class="garbage-icon" style="fill: green"

**Comment by SdeGeata** [comment]
Hey there!

   I'd like to chime in here to second this request. I would like to add custom icons for the Christmas Tree, oversized items and yard waste. How would I go about doing this in the Custom.css???

**Comment by htilburgs** [comment]
Updated 12-06-2023
- Added PMDBin (Yellow)
- Added OtherBin (Brown)

**Comment by kevbodavidson** [comment]
I would like custom icons as well to keep my screen all black and white (recycle logo instead of bin logo).. It would also help distinguish for bin cleaning day with a soap icon
